version: "3"

services:
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: redis:6.0.10-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redisData:/data
      - ./redis.conf:/etc/redis/redis.conf

  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - 7000:7000
    volumes:
      - ./nginx.docker.conf:/etc/nginx/nginx.conf
      - ./public/:/usr/share/nginx/html/public/ # public folder must be generated beforehand

  envoy:
    image: envoyproxy/envoy-alpine:v1.17-latest
    ports:
      - 80:80
      - 9901:9901
    volumes:
      - ./envoy-docker.yaml:/etc/envoy/envoy.yaml
      - ./envoy_logs:/var/log
    environment:
      # this is done because there were some permission issues.
      # learn more here: https://www.envoyproxy.io/docs/envoy/latest/start/docker#start-docker
      - ENVOY_UID=0

volumes:
  postgres:
